load_balancer_ws/urls.py
from django.contrib import admin
from django.urls import path, include

from load_balancer_ws.views import HomepageView

urlpatterns = [
    path('', HomepageView.as_view(), name='home'),
    path('worker/', include('workernode.urls')),
    path('admin/', admin.site.urls),
]

workernode/urls.py
from django.urls import path
from workernode import views

app_name = "workernode"

urlpatterns = [
    path("<int:pk>/start/", views.StartWorkerView.as_view(), name="start"),
    path("chart/", views.LiveChartView.as_view(), name="livechart"),
    path("error/<int:ex>/", views.NoWorkerAvailableView.as_view(), name="error"),
    path("execution/save/", views.save_analysis_ajax, name="execution-save"),
    path("execution/list/", views.ExecutionListView.as_view(), name="execution-list"),
    path("execution/<int:pk>/detail/", views.ExecutionDetailView.as_view(), name="execution-detail"),
]

workernode/models.py
import urllib3
import json

from django.db import models
import requests
import celery

import config


class Task(models.Model):
    TASK_1 = 1
    TASK_2 = 2
    TASK_3 = 3
    TASK_CHOICE = [
        (TASK_1, "1 - Find prime numbers in interval"),
        (TASK_2, "2 - Calculate a pow of each millisecond"),
        (TASK_3, "3 - Calculate the factorial of a number"),
    ]
    DEFAULT_OPS = 100
    DEFAULT_INTERVAL = 999
    DEFAULT_EXPONENT = 3
    DEFAULT_FACTORIAL = 30

    number = models.PositiveSmallIntegerField(choices=TASK_CHOICE, default=TASK_1)
    # this value will be updated each time through a form:
    ops = models.PositiveSmallIntegerField(default=DEFAULT_OPS)
    interval_value = models.PositiveSmallIntegerField(default=DEFAULT_INTERVAL)
    pow_exponent = models.PositiveSmallIntegerField(default=DEFAULT_EXPONENT)
    fact_number = models.PositiveSmallIntegerField(default=DEFAULT_FACTORIAL)

    def __str__(self):
        return f"number: {self.number}, ops: {self.ops}"

    @property
    def get_configuration(self):
        return {
            "task": json.dumps({
                "task_number": self.number,
                "custom_value": self.get_custom_value,
                "ops_value": self.ops,
            })
        }

    @property
    def get_free_configuration(self):
        return {"task": "Stop!"}

    @property
    def get_custom_value(self):
        if self.number == 1:
            return self.interval_value
        elif self.number == 2:
            return self.pow_exponent
        elif self.number == 3:
            return self.fact_number

    def get_help_configuration(self, ops):
        return {
            "task": json.dumps({
                "task_number": self.number,
                "custom_value": self.get_custom_value,
                "ops_value": ops,
            })
        }


class WorkerNode(models.Model):
    ip_address = models.CharField(max_length=15)
    available = models.BooleanField(default=True)
    reachable = models.BooleanField(default=True)
    current_ops = models.PositiveSmallIntegerField(default=0)
    task = models.ForeignKey(
        Task,
        on_delete=models.SET_NULL,
        related_name="task",
        null=True,
        blank=True,
    )

    def __str__(self):
        return f"ip: {self.ip_address}, av: {self.available}, rc: {self.reachable}"

    @classmethod
    def get_available_nodes(cls):
        return cls.objects.filter(available=True, reachable=True).all()

    @classmethod
    def get_busy_nodes(cls):
        return cls.objects.filter(available=False, reachable=True).all()

    @staticmethod
    def __send_json_http_request(url, json_data):
        headers = {"content-type": "application/json", }
        try:
            r = requests.put(
                url,
                json=json_data,
                headers=headers,
                timeout=config.REQUEST_TIMEOUT
            )
        except requests.exceptions.ConnectTimeout:
            return False
        except urllib3.exceptions.HTTPError:
            return False

        return True if r.status_code == 200 else False

    def bind(self, task):
        """Bind the task object to the working node."""
        self.task = task
        self.save()

    def set_busy(self):
        """Set the node not available for other executions."""
        self.available = False
        self.save()

    def set_unreachable(self):
        """The node is disconnected, set it unreachable."""
        self.reachable = False
        self.save()

    def set_reachable(self):
        """The node is reconnected, set it reachable."""
        self.reachable = True
        self.save()

    def set_current_ops(self, ops):
        """Update the op/s that the node is executing."""
        self.current_ops = ops
        self.save()

    def start_physical_twin(self, help_request=False, **kwargs):
        """This function sends an HTTP request to the physical node in
        order to start the execution requested by the user. A node can
        be the leader of the execution or a leader helper (in this case
        it must process a different value of op/s).
        """
        url = f"http://{self.ip_address}/things/task-execution/properties/task"

        if not help_request:
            json_data = self.task.get_configuration
            ops = self.task.ops
        else:
            json_data = self.task.get_help_configuration(kwargs["ops"])
            ops = kwargs["ops"]

        status = self.__send_json_http_request(
            url=url,
            json_data=json_data
        )
        if not status:
            self.set_unreachable()
            self.free(available=False)
            raise Exception(f"Can't connect to worker {self.ip_address}. Timeout.")

        self.set_current_ops(ops)
        self.set_busy()

    def sync_help_request(self, ops_needed):
        """Once the load balancer ask help to a new node, this function
        bind the task to the new helper and the starts it physically.
        """
        self.start_physical_twin(help_request=True, ops=ops_needed)

    def sync_launch(self, task):
        """This function only applies in case the current execution
        leader became dead, a new node must be started synchronously.
        """
        self.bind(task)
        self.start_physical_twin()

    def sync_update_ops(self, current_ops, operand):
        """This function is just an interface to the asynchronous
        update of the op/s that a node has to produce.
        """
        self.async_update_ops(operand(current_ops, config.OPS_UNIT))

    def async_launch(self, task):
        """This function only starts the async celery task."""
        self.bind(task)
        celery.current_app.send_task(
            "workernode.tasks.execute_task",
            args=(self.pk, config.TASK_DURATION, )
        )

    def async_help_request(self, task, current_ops, ops_requested):
        """Once the load balancer ask help to a new node, this function
        bind the task to the new helper and the starts it physically.
        In an asynchronous way.
        """
        self.bind(task)
        celery.current_app.send_task(
            "workernode.tasks.start_worker",
            args=(self.pk, ),
            kwargs={"current_ops": current_ops, "ops_requested": ops_requested}
        )

    def async_update_ops(self, new_ops):
        """Interface that hide the same call to help_request but with a
        different number of operations per second.
        """
        celery.current_app.send_task(
            "workernode.tasks.start_worker",
            args=(self.pk, True, ),
            kwargs={"new_ops": new_ops}
        )

    def free(self, available=True):
        """This function stops the execution on the physical node."""
        if available:
            status = self.__send_json_http_request(
                f"http://{self.ip_address}/things/task-execution/properties/task",
                self.task.get_free_configuration
            )
            if not status:
                self.set_unreachable()
                # this Exception can be logged
                print(f"Free - Can't connect to worker: {self.ip_address}. Timeout.")

        self.set_current_ops(0)
        self.task = None
        self.available = True
        self.save()


class Execution(models.Model):
    json_data = models.TextField()
    task_number = models.PositiveSmallIntegerField(default=0)
    task_ops = models.PositiveSmallIntegerField(default=0)
    workers_num = models.PositiveSmallIntegerField(default=0)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"Execution of Task[{self.task_number}] on {self.date}"

workernode/forms.py
from django import forms
from django.core.exceptions import ValidationError

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, Submit

from workernode.models import Task, WorkerNode


class TaskForm(forms.ModelForm):
    """Launch task for worker nodes."""

    helper = FormHelper()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper.layout = Layout(
            Row(
                Column("number", css_class="form-group"),
                css_class="form-row",
            ),
            Row(
                Column("interval_value", css_class="form-group task-1 d-none"),
                Column("pow_exponent", css_class="form-group task-2 d-none"),
                Column("fact_number", css_class="form-group task-3 d-none"),
                css_class="form-row",
            ),
            Row(
                Column("ops", css_class="form-group mb-0"),
                Column(
                    Submit("submit", "Launch", css_class="btn site-btn mb-3 w-75 font-5"),
                    css_class="d-flex align-items-end justify-content-end"
                ),
                css_class="form-row",
            ),
        )

    def clean(self):
        if self.cleaned_data["interval_value"] > self.instance.DEFAULT_INTERVAL:
            raise ValidationError(
                "Ensure the [ interval ] is less than or equal to 999.",
                code="invalid"
            )

        return super().clean()

    class Meta:
        model = Task
        fields = (
            "number",
            "ops",
            "interval_value",
            "pow_exponent",
            "fact_number",
        )
        labels = {
            "number": "Task type",
            "ops": "Operation per seconds",
            "interval_value": "Search interval for prime numbers (max: 999)",
            "pow_exponent": "Exponent of the pow",
            "fact_number": "Starting number",
        }

workernode/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView, UpdateView, ListView, DetailView
from django.urls import reverse_lazy

from workernode.forms import TaskForm
from workernode.models import Task, WorkerNode, Execution


class StartWorkerView(UpdateView):
    model = Task
    template_name = "workernode/task_form.html"
    form_class = TaskForm
    success_url = reverse_lazy("workernode:livechart")

    def form_valid(self, form):
        self.object = form.save()

        if available_nodes := WorkerNode.get_available_nodes():
            available_nodes[0].async_launch(self.object)
        else:
            return HttpResponseRedirect(
                reverse_lazy(
                    "workernode:error",
                    kwargs={"ex": 1}
                )
            )
        # return super().form_valid(form)
        return HttpResponseRedirect(self.get_success_url())


class LiveChartView(TemplateView):
    template_name = "workernode/live_chart.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["task"] = Task.objects.get(pk=1)

        return context


class NoWorkerAvailableView(TemplateView):
    template_name = "workernode/worker_error.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["ex"] = self.kwargs.get("ex")

        return context


class ExecutionListView(ListView):
    model = Execution
    template_name = "workernode/executions_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context["task"] = Task.objects.get(pk=1)

        return context


class ExecutionDetailView(DetailView):
    model = Execution
    template_name = "workernode/execution_detail.html"


@require_POST
@csrf_protect
def save_analysis_ajax(request):
    if request.method == "POST":
        Execution.objects.create(
            json_data=request.POST.get("execution"),
            task_number=request.POST.get("task_number"),
            task_ops=request.POST.get("task_ops"),
            workers_num=request.POST.get("workers_num")
        )

        return JsonResponse({'status': 'OK'})

workernode/templates/workernode/execution_detail.html
{% extends 'base.html' %}
{% load static %}
{% load app_filters %}

{% block title %}{{ block.super }}Execution Detail{% endblock %}

{% block content %}
    <div id="wrapper" class="site-box">
        <div class="row justify-content-center mt-5">
            <div class="col-lg-5 col-12">
                <a href="{% url 'workernode:execution-list'%}" class="font-6 site-blue-text flat-link">
                    <i class="fas fa-chevron-left me-2"></i>  Go back to Execution List
                </a>
                <h2 class="mb-5 font-7 logo-font site-color mt-3 ">
                    Execution {{ execution.pk }} - executed on {{ execution.date|date:"d/m/Y" }}
                </h2>
            </div>
        </div>
        <div class="row justify-content-center align-items-center pb-5">
            <div class="col-md-9 col-12">
                <canvas id="myChart"></canvas>
            </div>
            <div class="col-sm">
                <ul class="list-group">
                    <li class="list-group-item">
                        <p class="logo-font mt-4 h5 site-color d-flex justify-content-between">
                            <span>Task:</span> <span class="site-body-text">{{ execution.task_number|get_task_from_int }}</span>
                        </p>
                    </li>
                    <li class="list-group-item">
                        <p class="logo-font mt-4 h5 site-color d-flex justify-content-between">
                            <span>Operation/s requested:</span> <span class="site-body-text">{{ execution.task_ops }} op/s</span>
                        </p>
                    </li>
                    <li class="list-group-item">
                        <p class="logo-font mt-4 h5 site-color d-flex justify-content-between">
                            <span>Number of active Workers:</span>
                            <span id="workers_num" class="site-body-text">{{ execution.workers_num }}</span>
                        </p>
                    </li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_javascript %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.3.2"></script>
    <script src="https://cdn.jsdelivr.net/npm/luxon@1.27.0"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-luxon@1.0.0"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-streaming@2.0.0"></script>
    <script src="https://cdn.jsdelivr.net/npm/hammerjs@2.0.8"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-zoom@1.2.0/dist/chartjs-plugin-zoom.min.js"
            integrity="sha256-23gWVYds+PNFbnldeTaY5stxoJ6j+5QmR/vGLWpNcOg="
            crossorigin="anonymous"></script>
    <script>
        function buildChart() {
            let ctx = document.getElementById('myChart').getContext('2d');
            return new Chart(ctx, config);
        }

        const json_data = {{ execution.json_data|safe }};

        // CHART CREATION
        const config = {
            type: 'line',
            data: json_data,
            options: {
                legend: {
                    display: false
                },
                hover: {
                    mode: 'index',
                    intersec: false
                },
                scales: {
                    y: {
                        title: {
                            display: true,
                            text: 'Operations/s'
                        },
                        min: 0,
                        ticks: {
                            stepSize: 50,
                        }
                    },
                    x: {
                        type: 'timeseries',
                    }
                },
                plugins: {
                    tooltip: {
                        mode: 'index',
                        intersect: false
                    },
                },
            }
        };

        const chart = buildChart();
    </script>
{% endblock %}

workernode/templates/workernode/executions_list.html
{% extends 'workernode/base/base_list.html' %}
{% load static %}
{% load app_filters %}

{% block title %}
    {{ block.super }}Executions
{% endblock %}

{% block extra_css %}
    <style>
        .group-parent {
            overflow: hidden;
        }
        .list-group {
            max-height: 550px;
            overflow-y: scroll;
            scrollbar-width: none;  /* Works only in Firefox! */
        }
    </style>
{% endblock %}

{% block list_title %}
    Executions History
{% endblock %}

{% block list_button %}
    <div class="row justify-content-center">
        <div class="col-xl-3 col-lg-5 col-md-9 col-12 d-flex justify-content-between align-items-center">
            <a href="{% url 'home' %}" class="font-6 site-blue-text flat-link">
                <i class="fas fa-chevron-left me-2"></i>
                Go back to Home
            </a>
            <a href="{% url 'workernode:start' task.pk %}"
               class="btn site-btn font-5" style="width: auto !important;">
                Task Launcher
                <i class="fas fa-rocket ms-2"></i>
            </a>
        </div>
    </div>
{% endblock %}

{% block list_body %}
    {% for execution in execution_list %}
        <a href="{% url 'workernode:execution-detail' execution.pk %}" target="_blank"
           class="list-group-item list-group-item-action d-flex gap-3 py-3"
           aria-current="true">
            <img src="{% static 'img/gears.png' %}" alt="res" width="32" height="32"
                 class="flex-shrink-0 mr-3">
            <div class="d-flex gap-2 w-100 justify-content-between">
                <div>
                    <h6 class="mb-0">{{ execution.task_number|get_task_from_int }}</h6>
                    <p class="mb-0 opacity-75 font-size-80 font-4">
                        Executed on: {{ execution.date|date:"d/m/Y" }} -
                        <strong>
                            by {{ execution.workers_num }}
                            {% if execution.workers_num > 1 %}
                                workers
                            {% else %}
                                worker
                            {% endif %}
                        </strong>
                    </p>
                    <p class="mb-0 opacity-75">
                        Requested {{ execution.task_ops }} op/s
                    </p>
                </div>
                <small class="opacity-50 text-nowrap">Ex: {{ execution.pk }}</small>
            </div>
        </a>
    {% empty %}
        <a href="#"
           class="list-group-item list-group-item-action d-flex gap-3 py-3"
           aria-current="true">
            <img src="{% static 'img/empty.png' %}" alt="res" width="32" height="32"
                 class="flex-shrink-0 mr-3">
            <div class="d-flex gap-2 w-100 justify-content-between">
                <div>
                    <h6 class="mb-0">No executions yet!</h6>
                    <p class="mb-0 opacity-75">
                        Let's launch your <strong>first task</strong>!
                    </p>
                </div>
                <small class="opacity-50 text-nowrap"></small>
            </div>
        </a>
    {% endfor %}
{% endblock %}

workernode/templates/workernode/live_chart.html
{% extends 'base.html' %}
{% load static %}
{% load app_filters %}

{% block title %}{{ block.super }}Live Chart{% endblock %}

{% block content %}
    <div id="wrapper" class="site-box">
        <div class="row justify-content-center mt-5">
            <div class="col-lg-5 col-12">
                <a href="{% url 'workernode:start' task.pk %}" class="font-6 site-blue-text flat-link">
                    <i class="fas fa-chevron-left me-2"></i>  Go back to Task Launcher
                </a>
                <h2 class="mb-5 font-7 logo-font site-color mt-3 ">
                    Op/s executed by Workers
                </h2>
            </div>
        </div>
        <div class="row justify-content-center align-items-center pb-5">
            <div class="col-md-9 col-12">
                <canvas id="myChart"></canvas>
            </div>
            <div class="col-sm">
                <div class="alert alert-danger saturated" role="alert" style="display: none;">
                    <h5 class="alert-heading"><span class="me-2">Warning</span><i class="fas fa-exclamation-triangle"></i></h5>
                    <p class="mb-0">
                        No more workers available!
                    </p>
                </div>
                <div class="alert alert-danger exception" role="alert" style="display: none;">
                    <h5 class="alert-heading"><span class="me-2">Warning</span><i class="fas fa-exclamation-triangle"></i></h5>
                    <p class="mb-0 exception-message"></p>
                </div>
                <ul class="list-group">
                    <li class="list-group-item">
                        <p class="logo-font mt-4 h5 site-color d-flex justify-content-between">
                            <span>Executing Task:</span> <span class="site-body-text">{{ task.number|get_task_from_int }}</span>
                        </p>
                    </li>
                    <li class="list-group-item">
                        <p class="logo-font mt-4 h5 site-color d-flex justify-content-between">
                            <span>Operation/s requested:</span> <span class="site-body-text">{{ task.ops }} op/s</span>
                        </p>
                    </li>
                    <li class="list-group-item">
                        <p class="logo-font mt-4 h5 site-color d-flex justify-content-between">
                            <span>Number of active Workers:</span> <span id="workers_num" class="site-body-text"></span>
                        </p>
                    </li>
                </ul>
                <div class="d-flex justify-content-center">
                    <button id="save-ex" class="btn site-btn mt-5 mb-0 w-75">Save this execution</button>
                </div>
            </div>
        </div>
    </div>
    <div id="success-modal" class="modal fade">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title logo-font site-color" id="staticBackdropLabel">Execution saved &#9989;</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>The execution data is saved for further analysis.</p>
                    <p>
                        You can find it in the
                        <a href="{% url 'workernode:execution-list' %}" class="flat-link site-blue-text font-6">
                            Execution List <i class="fas fa-stream ms-1"></i>&nbsp;
                        </a>
                        page.
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn site-btn" data-bs-dismiss="modal">Great</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_javascript %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.3.2"></script>
    <script src="https://cdn.jsdelivr.net/npm/luxon@1.27.0"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-luxon@1.0.0"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-streaming@2.0.0"></script>
    <script src="https://cdn.jsdelivr.net/npm/hammerjs@2.0.8"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-zoom@1.2.0/dist/chartjs-plugin-zoom.min.js"
            integrity="sha256-23gWVYds+PNFbnldeTaY5stxoJ6j+5QmR/vGLWpNcOg="
            crossorigin="anonymous"></script>

    <script src="{% static 'js/live_chart.js' %}"></script>
    <script>
        const task_number = {{ task.number }};
        const task_ops = {{ task.ops }};

        function ajaxSaveExecution() {
            $.ajax({
                type: 'POST',
                url: '{% url "workernode:execution-save" %}',
                data: {
                    'execution': JSON.stringify(chart.data),
                    'task_number': task_number,
                    'task_ops': task_ops,
                    'workers_num': $('#workers_num').text(),
                },
                headers:{
                    "X-CSRFToken": '{{ csrf_token }}'
                },
                dataType: 'json',
                success: function (data) {
                    console.log(data);
                    let modal = new bootstrap.Modal(document.getElementById('success-modal'));
                    modal.show();
                }

            });
        }

        $('#save-ex').on('click', function () {
            ajaxSaveExecution();
        });
    </script>
{% endblock %}

workernode/templates/workernode/task_form.html
{% extends 'base_form.html' %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Task launcher{% endblock %}

{% block form_title %}Launch a Task{% endblock %}

{% block form_body %}
    {% crispy form %}
{% endblock %}

{% block back_url %}
    <a href="{% url 'home' %}" class="font-6 site-blue-text flat-link">
        <i class="fas fa-chevron-left me-2"></i>  Go back to Home
    </a>
{% endblock %}

{% block extra_javascript %}
    <script>
        $('#id_number').on('change', function () {
            if (this.value === "1") {
                $('.task-1').removeClass('d-none')
                $('.task-2').addClass('d-none')
                $('.task-3').addClass('d-none')
            } else if (this.value === "2") {
                $('.task-1').addClass('d-none')
                $('.task-2').removeClass('d-none')
                $('.task-3').addClass('d-none')
            } else if (this.value === "3") {
                $('.task-1').addClass('d-none')
                $('.task-2').addClass('d-none')
                $('.task-3').removeClass('d-none')
            }
        });

        $(document).ready(function () {
            $('#id_number').trigger('change');
        })
    </script>
{% endblock %}

workernode/templates/workernode/worker_error.html
{% extends 'base.html' %}
{% load static %}
{% load app_filters %}

{% block extra_css %}
{% endblock %}

{% block title %}{{ block.super }}Error{% endblock %}

{% block content %}
    <div class="site-box">
        <div class="row justify-content-center mt-5">
            <div class="col-lg-5 col-12">
                <span class="h2 site-color logo-font">Error</span>
                <div class="row mt-4 mb-3">
                    <div class="col">
                        <p class="text-muted font-5">
                            {{ ex|get_exception_from_int }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center align-items-center mt-5">
            <div class="col-xl-3 col-lg-5 col-md-9 col-12 d-flex flex-column align-items-start">
                <a href="{% url 'home' %}" class="btn site-btn mb-0">
                    Go back to Home
                </a>
            </div>
        </div>
    </div>
{% endblock %}